version: 2.0
jobs:
  build_artifact:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - checkout
  
      - run: git clone --depth 1 https://github.com/koseven/koseven.git --single-branch
      - run: 
          name: Build dtapi
          command: |
            ARTIFACT="artifact"
            mkdir "$ARTIFACT"
            
            cp -r koseven/modules "$ARTIFACT"
            cp -r koseven/system "$ARTIFACT"
            cp koseven/public/index.php "$ARTIFACT"
      
            cp -r application "$ARTIFACT"
            cp .htaccess "$ARTIFACT"
            mkdir -p "$ARTIFACT/application/cache/"
            mkdir -p "$ARTIFACT/application/logs/"
            tar -czf dtapi_be_artifact.tar.gz -C "./$ARTIFACT" .

      - store_artifacts: # store the uberjar as an artifact
          path: dtapi_be_artifact.tar.gz

workflows:
  version: 2
  build:
    jobs:
      - build_artifact
