version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.8.0
  gcp-gke: circleci/gcp-gke@1.1.0

jobs:
  build_artifact:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - checkout

      - run: git clone --depth 1 https://github.com/koseven/koseven.git --single-branch
      - run:
          name: Build dtapi
          command: |
            ARTIFACT="artifact"
            mkdir "$ARTIFACT"

            cp -r koseven/modules "$ARTIFACT"
            cp -r koseven/system "$ARTIFACT"
            cp koseven/public/index.php "$ARTIFACT"

            cp -r application "$ARTIFACT"
            cp .htaccess "$ARTIFACT"
            mkdir -p "$ARTIFACT/application/cache/"
            mkdir -p "$ARTIFACT/application/logs/"
            tar -czf dtapi_be_artifact.tar.gz -C "./$ARTIFACT" .

      - store_artifacts: # store the uberjar as an artifact
          path: dtapi_be_artifact.tar.gz

      - persist_to_workspace:
          root: .
          paths:
            - "artifact"
            - "docker"

  build-and-push-image:
    docker:
      - image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    resource_class: small
    steps:
      - setup_remote_docker 
      - attach_workspace:
          at: ~/project/
      - gcp-gcr/gcr-auth
      # build and push Docker image
      - gcp-gcr/build-image:
          dockerfile: "docker/Dockerfile"
          image: dtapi-be
          registry-url: eu.gcr.io
          tag: ${CIRCLE_SHA1:0:7}

      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: dtapi-be
          registry-url: eu.gcr.io
          tag: ${CIRCLE_SHA1:0:7}
      
      - gcp-gcr/tag-image:
          image: dtapi-be
          registry-url: eu.gcr.io
          source-tag: ${CIRCLE_SHA1:0:7}
          target-tag: latest
      # The path to save the RepoDigest of the pushed image
      - run:
          name: sha256 Digest 
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

  deploy:
    docker:
      - image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    resource_class: small
    steps:
   
    - gcp-gcr/gcr-auth
    # Update a deployment Docker image.
    - gcp-gke/rollout-image:
        cluster: cluster-1
        deployment: $GCP_BE_DEPLOYMENT
        container: $GCP_BE_CONTAINER
        image: eu.gcr.io/$GOOGLE_PROJECT_ID/dtapi-be
        tag: ${CIRCLE_SHA1:0:7}
    
workflows:
  build:
    jobs:
      - build_artifact
      - build-and-push-image:
          context: dtapi
          requires:
            - build_artifact
      
      - deploy:
          context: dtapi
          requires:
            - build-and-push-image 
